config/routes.rb
Rails.application.routes.draw do
  
  # for registrations, look at user/registrations controller first, then devise
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  resources :user_stocks, except: [:show, :edit, :update]
  resources :users, only: [:show]
  resources :friendships
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'welcome#index'
  
  get 'my_portfolio', to: "users#my_portfolio"
  
  get 'search_stocks', to: "stocks#search"
  get 'my_friends', to: "users#my_friends"
  get 'search_friends', to: "users#search"
  post 'add_friend', to: "users#add_friend"
  
end

app/views/friends/_lookup.html.erb
<div id="friend-lookup">
  <h3>Search for Friends</h3>
  
  <%= form_tag search_friends_path, remote: true, method: :get, id: 'friend-lookup-form' do %>
    
    <div class="form-group row no-padding text-center col-md-12">
    
      <div class="col-md-10">
        <%= text_field_tag :search_param, params[:search_param], 
                            placeholder: 'First Name, last name or email', 
                            autofocus: true, 
                            class: 'form-control search-box input-lg' %>
      </div>
    
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: 'btn btn-lg btn-success') do %>
          <i class='fa fa-search'></i> Look up a friend
        <% end %>
      </div>
    
    </div>
  
  <% end %>
  
  <%= render 'common/spinner' %>
  
  <% if @users %>
    <% if @users.size > 0 %>
      <div id="friend-lookup-results" class="well results-block col-md-10">
        <table class="search-results-table col-md-12">
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><strong>Name:</strong> <%= user.full_name %></td>
                <td><strong>Email:</strong> <%= user.email %></td>
                <td><strong>Profile: </strong><%= link_to "View Profile" ,
                                              user_path(user),
                                              class: "btn btn-xs btn-success" %>
                  <% if current_user.not_friends_with?(user.id) %>
                    <%= link_to "Add as my friend", add_friend_path( user: current_user, friend: user),
                        class: "btn btn-xs btn-success", method: :post %>
                  <% else %>
                    <span class="label label-primary">
                      You are already friends
                    </span>
                  <% end %>
                </td
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% else %>
      <p class="lead">No people meet the criteria</p>
    <% end %>
  <% end %>
  <div id="friend-lookup-errors"></div>
  
</div>