config/routes.rb
Rails.application.routes.draw do
  
  # for registrations, look at user/registrations controller first, then devise
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  resources :user_stocks, except: [:show, :edit, :update]
  resources :users, only: [:show]
  resources :friendships
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'welcome#index'
  
  get 'my_portfolio', to: "users#my_portfolio"
  
  get 'search_stocks', to: "stocks#search"
  get 'my_friends', to: "users#my_friends"
  get 'search_friends', to: "users#search"
  post 'add_friend', to: "users#add_friend"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  
  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    return "Anonymous"
  end
  
  def can_add_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_added?(ticker_symbol)
  end
  
  def under_stock_limit?
    (user_stocks.count < 10)
  end
  
  def stock_already_added?(ticker_symbol)
    stock = Stock.find_by_ticker(ticker_symbol)
    return false unless stock
    user_stocks.where(stock_id: stock.id).exists?
  end
  
  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end
  
  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end
  
  def self.search(param)
    return User.none if param.blank?
    
    param.strip!
    param.downcase!
    ( first_name_matches(param)+last_name_matches(param)+email_matches(param)).uniq
  end
  
  def self.first_name_matches(param)
    matches( 'first_name', param)
  end

  def self.last_name_matches(param)
    matches( 'last_name', param)
  end  
  
  def self.email_matches(param)
    matches( 'email', param)
  end
  
  def self.matches(field_name, param)
    # % is wildcard
    where("lower(#{field_name}) like ?", "%#{param}%")
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters
end

private
def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user_stocks = current_user.stocks       
    @user = current_user
  end
    
  def my_friends
    @friendships = current_user.friends
  end
    
  def search
    @users = User.search(params[:search_param])
    
    if @users
      @users = current_user.except_current_user(@users)
      render partial: "friends/lookup"
    else
      render status: :not_found, nothing: true
    end
    
  end
  
  def add_friend
    @friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: @friend.id)
    
    if current_user.save
      redirect_to my_friends_path, notice: "Friend was successfully added"  
    else
      redirect_to my_friends_path, flash[:error] = "There was an error with adding user as friend"
    end
    
    def show
      @user = User.find(params[:id])
      @user_stocks = @user.stocks
    end
  end
end

app/views/users/my_friends.html.erb
<%= render "friends/lookup" %>

<% if @friendships.size > 0 %>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th colspan="3" class="page-header">
          <h2>My Friends</h2>
        </th>
      </tr>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
    
    <tbody>
      <% @friendships.each do |friend| %>
      <tr>
        <td><%= friend.full_name %></td>
        <td><%= friend.email %></td>
        <td><%= link_to "View Profile", user_path(friend), class: "btn btn-primary btn-xs" %>
            <%= link_to "Remove Friend", friendship_path(friend),
                                        :method => :delete,
                                        :data => { :confirm => "Are you sure?"},
                                        :class => "btn btn-danger btn-xs" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>                            
  
<% else %>
  <div class="col-lg-12">
    <p class="lead">You don't have any friends yet.  Add some.</p>
  </div>

<% end %>

app/views/users/my_portfolio.html.erb
<%= render 'stocks/lookup' %>

<%= render 'stocks/list' %>

app/views/users/show.html.erb
<h2>User Details</h2>

<dl class="dl-horizontal">
  <dt><strong>Name</strong></dt>
  <dd><%= @user.full_name %></dd>
  <dt><strong>Email</strong></dt>
  <dd><%= @user.email %></dd>
</dl>

<% if @user.stocks.size > 0 %>
  <%= render "stocks/list" %>
<% else %>
  <p class="lead">This user is not tracking any stocks</p>
<% end %>

<%= link_to "Back", my_friends_path, class: "btn btn-primary" %>